### ISSUE TITLE
Entrypoint woes

### ISSUE THREAD

**Issue by einar** [Internet2/comanage-registry-docker#11]
When running docker(s) we mount in /etc/passwd & group to be able to track users across containers; this is all neat when the dockerized applications do chown/chmod but horrible if they don't. When running the "comanage-registry-shibboleth-sp" we get a working key and cert, because they are chmod'ed and chown'ed, but a non-working shibboleth2.xml as it is only chmod'ed. Is it possible to get a chown on the xml as well? :) We have to run "chmod 666" on it now for it to load at all... ;(

(I'm also curious as to why /opt/shibboleth-sp is used as a minichroot for shib, or is it? Can't figure if it does or does not use /etc/shibboleth at all...)

**Comment by skoranda** [comment]
The /etc/shibboleth2.xml needs to only be readable by the _shibd user. A typical Shibboleth SP deployment will have that file owned by root and in group root with permissions 0644.

Commit 19486f7323e745d4bcf02db4f77353242164687c adds logic to the Shibboleth SP entry point script to make sure that files that must be owned by _shibd are owned by _shibd at runtime. This allows deployers to map _shibd to a specific UID and still have the daemon function.

The new code in that commit for the entrypoint script will also emit a WARNING if it finds any files in /etc/shibboleth that are not readable, since for most deployments all files in that directory would be readable. 

It does NOT just force files in that directory to be readable since we do not want to change permissions on files that a deployer might inject for other reasons.
